BEGIN;

ALTER TABLE account_roles
    ADD COLUMN IF NOT EXISTS color VARCHAR(7) NOT NULL DEFAULT '#475569';

ALTER TABLE account_roles
    ADD COLUMN IF NOT EXISTS icon VARCHAR(80) NOT NULL DEFAULT 'badge';

CREATE TABLE IF NOT EXISTS staff_access_seed_state (
    seed_key VARCHAR(120) PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
