<?php

declare(strict_types=1);

require_once dirname(__DIR__, 3) . '/lib/bootstrap.php';
require_once dirname(__DIR__, 3) . '/lib/administration.php';
require_once dirname(__DIR__, 3) . '/components/layout.php';
require_once dirname(__DIR__, 3) . '/components/ui.php';

staff_administration_require_admin($staffContext);
$pdo = staff_db();
$statuses=['draft'=>'下書き','published'=>'公開','hidden'=>'非公開'];
$categories=['site_update'=>'サイト更新','feature'=>'機能追加','important'=>'重要','maintenance'=>'メンテナンス','service'=>'サービス','other'=>'その他'];

if($_SERVER['REQUEST_METHOD']==='POST'){
    $id=(int)($_POST['id']??0);
    try{
        if(!csrf_check($_POST['csrf_token']??null)){throw new RuntimeException('操作の有効期限が切れました。');}
        $title=trim((string)($_POST['title']??''));$slug=trim((string)($_POST['slug']??''));$category=(string)($_POST['category']??'other');$summary=trim((string)($_POST['summary']??''));$body=trim((string)($_POST['body']??''));$status=(string)($_POST['status']??'draft');$published=trim((string)($_POST['published_at']??''));
        $hasImage=isset($_POST['has_image']);$image=trim((string)($_POST['image_path']??''));$hasLink=isset($_POST['has_related_link']);$url=trim((string)($_POST['related_url']??''));$button=trim((string)($_POST['related_button_text']??''));$pinned=isset($_POST['is_pinned']);
        if($title===''||mb_strlen($title)>180){throw new RuntimeException('タイトルを180文字以内で入力してください。');}
        if(!preg_match('/^[a-z0-9-]+$/',$slug)||mb_strlen($slug)>140){throw new RuntimeException('slugは半角英数字とハイフンで入力してください。');}
        if(!isset($categories[$category])||!isset($statuses[$status])){throw new RuntimeException('カテゴリまたは公開状態が不正です。');}
        if($summary===''||$body===''){throw new RuntimeException('概要と本文を入力してください。');}
        try{$publishedAt=(new DateTime($published))->format('Y-m-d H:i:s');}catch(Throwable $e){throw new RuntimeException('公開日時が不正です。');}
        if($hasImage&&($image===''||(!str_starts_with($image,'/')&&!filter_var($image,FILTER_VALIDATE_URL)))){throw new RuntimeException('画像パスを正しく入力してください。');}
        if($hasLink&&($url===''||$button===''||(!str_starts_with($url,'/')&&!filter_var($url,FILTER_VALIDATE_URL)))){throw new RuntimeException('関連リンクとボタン文言を正しく入力してください。');}
        $dup=$pdo->prepare('SELECT id FROM news WHERE slug=:slug AND id<>:id');$dup->execute(['slug'=>$slug,'id'=>$id]);if($dup->fetch()){throw new RuntimeException('このslugはすでに使用されています。');}
        $params=['title'=>$title,'slug'=>$slug,'category'=>$category,'summary'=>$summary,'body'=>$body,'has_image'=>$hasImage?'true':'false','image'=>$hasImage?$image:null,'has_link'=>$hasLink?'true':'false','url'=>$hasLink?$url:null,'button'=>$hasLink?$button:null,'pinned'=>$pinned?'true':'false','status'=>$status,'published'=>$publishedAt];
        if($id>0){$params['id']=$id;$stmt=$pdo->prepare('UPDATE news SET title=:title,slug=:slug,category=:category,summary=:summary,body=:body,has_image=CAST(:has_image AS BOOLEAN),image_path=:image,has_related_link=CAST(:has_link AS BOOLEAN),related_url=:url,related_button_text=:button,is_pinned=CAST(:pinned AS BOOLEAN),status=:status,published_at=:published,updated_at=NOW() WHERE id=:id');$stmt->execute($params);staff_administration_flash('success','ニュースを更新しました。');}
        else{$stmt=$pdo->prepare('INSERT INTO news(title,slug,category,summary,body,has_image,image_path,has_related_link,related_url,related_button_text,is_pinned,status,published_at,created_at,updated_at) VALUES(:title,:slug,:category,:summary,:body,CAST(:has_image AS BOOLEAN),:image,CAST(:has_link AS BOOLEAN),:url,:button,CAST(:pinned AS BOOLEAN),:status,:published,NOW(),NOW()) RETURNING id');$stmt->execute($params);$id=(int)$stmt->fetchColumn();staff_administration_flash('success','ニュースを追加しました。');}
    }catch(Throwable $e){staff_administration_flash('error',$e->getMessage());}
    staff_administration_redirect('/staff/admin/site/news/?id='.max(0,$id));
}

$query=trim((string)($_GET['q']??''));$filterStatus=(string)($_GET['status']??'');$filterCategory=(string)($_GET['category']??'');$where=['1=1'];$params=[];
if($query!==''){$where[]='(title ILIKE :q OR slug ILIKE :q OR summary ILIKE :q OR body ILIKE :q)';$params['q']='%'.$query.'%';}
if(isset($statuses[$filterStatus])){$where[]='status=:status';$params['status']=$filterStatus;}else{$filterStatus='';}if(isset($categories[$filterCategory])){$where[]='category=:category';$params['category']=$filterCategory;}else{$filterCategory='';}
$stmt=$pdo->prepare('SELECT * FROM news WHERE '.implode(' AND ',$where).' ORDER BY is_pinned DESC,published_at DESC NULLS LAST,id DESC');$stmt->execute($params);$items=$stmt->fetchAll()?:[];
$selectedId=(int)($_GET['id']??0);$selected=null;if($selectedId>0){$stmt=$pdo->prepare('SELECT * FROM news WHERE id=:id');$stmt->execute(['id'=>$selectedId]);$selected=$stmt->fetch()?:null;}
$form=$selected?:['id'=>0,'title'=>'','slug'=>'','category'=>'other','summary'=>'','body'=>'','has_image'=>false,'image_path'=>'','has_related_link'=>false,'related_url'=>'','related_button_text'=>'','is_pinned'=>false,'status'=>'draft','published_at'=>date('Y-m-d H:i:s')];
$publishedLocal=$form['published_at']?date('Y-m-d\TH:i',strtotime((string)$form['published_at'])):'';$flash=staff_administration_take_flash();
staff_layout_start(['title'=>'ニュース管理','heading'=>'ニュース管理','eyebrow'=>'WEBSITE / NEWS','description'=>'公開サイトのお知らせを作成し、本文、画像、関連リンク、固定表示と公開状態を管理します。']);
?>
<div class="ops-page admin-native-page"><?php if($flash):?><div class="ops-alert <?=$flash['type']==='success'?'ops-alert--success':''?>"><?=staff_ui_escape($flash['message'])?></div><?php endif;?>
<form class="ops-toolbar" method="get"><label class="ops-toolbar__field"><span class="ops-label">検索</span><input class="ops-input" name="q" value="<?=staff_ui_escape($query)?>" placeholder="タイトル・slug・本文"></label><label><span class="ops-label">カテゴリ</span><select class="ops-select" name="category"><option value="">すべて</option><?php foreach($categories as $v=>$l):?><option value="<?=$v?>" <?=$filterCategory===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label><span class="ops-label">状態</span><select class="ops-select" name="status"><option value="">すべて</option><?php foreach($statuses as $v=>$l):?><option value="<?=$v?>" <?=$filterStatus===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><button class="ops-button" type="submit">検索</button><a class="ops-button ops-button--secondary" href="/staff/admin/site/news/">新規追加</a></form>
<div class="ops-split"><section class="ops-list"><header class="ops-panel__header"><div><h3>ニュース一覧</h3><p><?=count($items)?>件</p></div></header><div class="ops-rows"><?php foreach($items as $item):?><a class="ops-row <?=(int)$item['id']===$selectedId?'is-selected':''?>" href="?id=<?=(int)$item['id']?>"><span><strong class="ops-row__title"><?=!empty($item['is_pinned'])?'★ ':''?><?=staff_ui_escape($item['title'])?></strong><span class="ops-row__meta"><?=staff_ui_escape($categories[$item['category']]??$item['category'])?> / <?=staff_ui_escape($item['summary'])?></span></span><span class="ops-row__end"><span class="ops-status ops-status--<?=staff_ui_escape($item['status'])?>"><?=staff_ui_escape($statuses[$item['status']]??$item['status'])?></span><span class="ops-row__meta"><?=staff_ui_escape(staff_administration_datetime($item['published_at']))?></span></span></a><?php endforeach;?></div></section>
<section class="ops-detail"><header class="ops-panel__header"><div><h3><?=$selected?'ニュースを編集':'新しいニュースを追加'?></h3><p><?=$selected?'ニュース #'.(int)$selected['id']:'下書き保存できます。'?></p></div></header><div class="ops-panel__body"><form method="post" class="admin-native-form"><input type="hidden" name="csrf_token" value="<?=staff_ui_escape(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$form['id']?>"><div class="ops-form-grid"><label><span class="ops-label">タイトル</span><input class="ops-input" name="title" value="<?=staff_ui_escape($form['title'])?>" required></label><label><span class="ops-label">slug</span><input class="ops-input" name="slug" value="<?=staff_ui_escape($form['slug'])?>" required></label><label><span class="ops-label">カテゴリ</span><select class="ops-select" name="category"><?php foreach($categories as $v=>$l):?><option value="<?=$v?>" <?=$form['category']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label><span class="ops-label">公開状態</span><select class="ops-select" name="status"><?php foreach($statuses as $v=>$l):?><option value="<?=$v?>" <?=$form['status']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label><span class="ops-label">公開日時</span><input class="ops-input" type="datetime-local" name="published_at" value="<?=staff_ui_escape($publishedLocal)?>" required></label></div><label class="admin-native-field"><span class="ops-label">概要</span><textarea class="ops-textarea" name="summary" rows="3" required><?=staff_ui_escape($form['summary'])?></textarea></label><label class="admin-native-field"><span class="ops-label">本文</span><textarea class="ops-textarea" name="body" rows="9" required><?=staff_ui_escape($form['body'])?></textarea></label><div class="ops-form-grid"><label><span class="ops-check"><input type="checkbox" name="has_image" value="1" <?=!empty($form['has_image'])?'checked':''?>>画像を表示</span><input class="ops-input" name="image_path" value="<?=staff_ui_escape($form['image_path'])?>" placeholder="/storage/news/image.png"></label><label><span class="ops-check"><input type="checkbox" name="has_related_link" value="1" <?=!empty($form['has_related_link'])?'checked':''?>>関連ボタンを表示</span><input class="ops-input" name="related_url" value="<?=staff_ui_escape($form['related_url'])?>" placeholder="/services/"><input class="ops-input" name="related_button_text" value="<?=staff_ui_escape($form['related_button_text'])?>" placeholder="詳しく見る"></label></div><label class="ops-check"><input type="checkbox" name="is_pinned" value="1" <?=!empty($form['is_pinned'])?'checked':''?>>一覧の先頭に固定</label><div class="ops-form-actions"><button class="ops-button" type="submit"><?=$selected?'変更を保存':'ニュースを追加'?></button></div></form></div></section></div></div>
<?php staff_layout_end();
